/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/footer/Footer.vue')['default']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    IconPark: typeof import('./src/components/common/iconPark.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MenuList: typeof import('./src/components/layout/menu/menuList.vue')['default']
    MoreText: typeof import('./src/components/common/moreText.vue')['default']
    PlayerAction: typeof import('./src/components/layout/footer/playerAction.vue')['default']
    PlayerController: typeof import('./src/components/layout/footer/playerController.vue')['default']
    PlayerSlier: typeof import('./src/components/layout/footer/playerSlier.vue')['default']
    PlayerSong: typeof import('./src/components/layout/footer/playerSong.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPop: typeof import('./src/components/layout/header/searchPop.vue')['default']
    SearchSuggest: typeof import('./src/components/layout/header/searchSuggest.vue')['default']
    UserInfo: typeof import('./src/components/layout/header/userInfo.vue')['default']
  }
}
