/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CAlbum: typeof import('./src/components/common/CAlbum.vue')['default']
    CArtist: typeof import('./src/components/common/CArtist.vue')['default']
    Comment: typeof import('./src/components/common/Comment.vue')['default']
    CommentList: typeof import('./src/components/common/CommentList.vue')['default']
    CPagination: typeof import('./src/components/common/CPagination.vue')['default']
    CPlaylist: typeof import('./src/components/common/CPlaylist.vue')['default']
    CVideo: typeof import('./src/components/common/CVideo.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./src/components/layout/footer/Footer.vue')['default']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    List: typeof import('./src/components/layout/menu/List.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MenuList: typeof import('./src/components/layout/menu/menuList.vue')['default']
    MoreText: typeof import('./src/components/common/moreText.vue')['default']
    MusicList: typeof import('./src/components/common/MusicList.vue')['default']
    MyList: typeof import('./src/components/layout/menu/myList.vue')['default']
    PlayerAction: typeof import('./src/components/layout/footer/playerAction.vue')['default']
    PlayerController: typeof import('./src/components/layout/footer/playerController.vue')['default']
    PlayerSlier: typeof import('./src/components/layout/footer/playerSlier.vue')['default']
    PlayerSong: typeof import('./src/components/layout/footer/playerSong.vue')['default']
    PlayerVolumeSlider: typeof import('./src/components/layout/footer/playerVolumeSlider.vue')['default']
    PlayList: typeof import('./src/components/layout/playList/PlayList.vue')['default']
    Popup: typeof import('./src/components/layout/playList/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPop: typeof import('./src/components/layout/header/searchPop.vue')['default']
    SearchSuggest: typeof import('./src/components/layout/header/searchSuggest.vue')['default']
    UserInfo: typeof import('./src/components/layout/header/userInfo.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
